### ISSUE TITLE
Plugin overrides system-native settings shortcut on macOS

### ISSUE THREAD

**Issue by coreyward** [CasperLaiTW/ERBAutocomplete#9]
[This default shortcut](https://github.com/CasperLaiTW/ERBAutocomplete/blob/master/Default%20(OSX).sublime-keymap#L8-L13) conflicts with the OS X / macOS default that Sublime Text also uses.

**Comment by CasperLaiTW** [comment]
Hi @coreyward 

Thanks for report.

I fixed `1.3.0`, please upgrade.

I merge mark and unmark into the same key binding `(command+.)`

enjoy it
